name: "test: windows"
on: [push]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22, 1.23, 1.24, 1.25]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}
          cache: false

      - name: Run tests and generate coverage
        run: go test ./... -v
