name: test
on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.22, 1.23]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - name: Run tests and generate coverage
        run: go test -v -coverprofile=coverage.out -coverpkg=.

      - name: Check coverage threshold
        run: |
          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          if (( $(echo "$coverage < 80.0" | bc -l) )); then
            exit 1
          fi

      - name: Go vet
        run: go vet ./...
