name: test
on: [push]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1, 1.18, 1.22, 1.23]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}

      - name: Run tests and generate coverage
        run: go test ./...
